services:
  mongodb:
    image: mongo:latest
    container_name: mongo-scraper
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    networks:
      - scraper-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: always

volumes:
  mongo_data:

networks:
  scraper-net:
    driver: bridge
